In [ ]:
from google.colab import files
files.upload()


Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"yazhini4225","key":"1a6ba5ceade148cb5a7831e69292e05b"}'}

In [ ]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!pip install kaggle

In [ ]:
!kaggle competitions download -c titanic

  0% 0.00/34.1k [00:00<?, ?B/s]
100% 34.1k/34.1k [00:00<00:00, 127MB/s]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(np.dot(a,b))

[5 7 9]
[ 4 10 18]
32


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
print(a+b)
print(a*b)
print(np.dot(a,b))
print(np.mean(a))
print(np.mean(b))

[ 5  7  9 11 13]
[ 4 10 18 28 40]
100
3.0
6.0


In [ ]:
!kaggle competitions download -c titanic
!unzip titanic.zip

titanic.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  titanic.zip
  inflating: gender_submission.csv   
  inflating: test.csv                
  inflating: train.csv               


In [ ]:
import pandas as pd
df=pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
len(df)

891

In [ ]:
df.shape

(891, 12)

In [ ]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# The 'Cabin' column has already been dropped, so this line is no longer needed.
# df.drop(columns=['Cabin'], inplace=True)

In [ ]:
df.fillna({'Age': df['Age'].median()}, inplace=True)

In [ ]:
df.fillna({'Embarked': df['Embarked'].mode()[0]}, inplace=True)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [ ]:
df['Sex']=df['Sex'].map({'male':0,'female':1})

In [ ]:
df['Embarked']=df['Embarked'].map({'S':0,'C':1,'Q':2})

In [ ]:
print(df[['Sex', 'Embarked']].head())

   Sex  Embarked
0    0         0
1    1         1
2    1         0
3    1         0
4    0         0


In [ ]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
target = 'Survived'

In [ ]:
x=df[features]
y=df[target]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=200) #max_iter to prevent infinate loops and helps to converge
model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [ ]:
y_pred=model.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.7988826815642458


In [ ]:
new_passenger = [[3, 0, 35, 0, 0, 7.25, 0]]

prediction = model.predict(new_passenger)
print("Prediction:", prediction)

Prediction: [0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
passengers = [
    [1, 1, 29, 0, 0, 100, 1],
    [3, 0, 40, 1, 3, 8.05, 0]
]

predictions = model.predict(passengers)
print("Predictions:", predictions)


Predictions: [1 0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
probabilities = model.predict_proba(passengers)
print("Survival probabilities:", probabilities)

Survival probabilities: [[0.05473797 0.94526203]
 [0.95614335 0.04385665]]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()

param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'max_iter': [200, 500, 1000]
}

grid_search = GridSearchCV(log_reg, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

best_params = grid_search.best_params_
print("Best parameters:", best_params)


Best parameters: {'C': 0.01, 'max_iter': 200}


In [ ]:
best_model = LogisticRegression(
    C=best_params['C'],
    max_iter=best_params['max_iter']
)
best_model.fit(X_train_scaled, y_train)

from sklearn.metrics import accuracy_score
y_pred = best_model.predict(X_test_scaled)
print("Improved Accuracy:", accuracy_score(y_test, y_pred))


Improved Accuracy: 0.7932960893854749


In [47]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

Precision: 0.7936507936507936


In [48]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.6756756756756757


In [49]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[92 13]
 [24 50]]


In [50]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.6756756756756757


In [51]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.7299270072992701


In [52]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       105
           1       0.79      0.68      0.73        74

    accuracy                           0.79       179
   macro avg       0.79      0.78      0.78       179
weighted avg       0.79      0.79      0.79       179

